model_params:
  MODEL: llama3.2
  CHUNK_SIZE: 10
  SUMMARY_LIMIT: 150
  BULLETS: 5
  BATCH_CHUNKS: 2
  PROVIDER: ollama
  VECTOR_DB: pgvector
ollama_params:
  stream: false
  keep_alive: 10m
responses:
  VIDEO_NOT_SUMMARISED:
    status: VIDEO_NOT_SUMMARISED
    message: The video could not be summarised
  VIDEO_SUMMARISED_SUCCESSFULLY:
    status: VIDEO_SUMMARISED_SUCCESSFULLY
    message: The video was successfully summarised using AI
  VIDEO_RETRIEVED_SUCCESSFULLY:
    status: VIDEO_RETRIEVED_SUCCESSFULLY
    message: The video was successfully retieved
endpoint:
  api_prefix: /api/v1
  algorithm: HS256
  access_token_expire_minutes: 30
  token_method: /token
supported_websites:
  - www.youtube.com
