model_params:
  MODEL: gpt-4-1106-preview
  CHUNK_SIZE: 10
  SUMMARY_LIMIT: 150
  BULLETS: 5
  BATCH_CHUNKS: 2
responses:
  ERROR:
    status: VIDEO_NOT_SUMMARISED
    message: "The video could not be summarised"
  SUCCESS:
    status: VIDEO_SUMMARISED_SUCCESSFULLY
    message: "The video was successfully summarised using AI"
endpoint: http://0.0.0.0:12000/api/v1/summarize_video